name: Backend/Frontend CI

on:
  push:
    branches: ["main"] # trigger on push to main (as per reference)
  pull_request:
    branches: ["main", "features"] # also run on PRs

jobs:
  test-and-build:
    # Reference uses self-hosted; keep that. If you don't have it yet, switch to ubuntu-latest temporarily.
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # optional: print secrets names (do NOT echo actual secrets in real projects)
      - name: Print env names (demo)
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "MONGO_URI set? ${{ secrets.MONGO_URI != '' }}"
          echo "JWT_SECRET set? ${{ secrets.JWT_SECRET != '' }}"
          echo "PORT set? ${{ secrets.PORT != '' }}"

      - name: Stop PM2 apps (CD prep)
        run: pm2 stop all || true

      - name: Install Backend deps
        working-directory: backend
        run: |
          npm i --global yarn
          yarn --version
          yarn install

      - name: Install Frontend deps + build
        working-directory: frontend
        run: |
          df -h || true
          rm -rf build || true
          yarn install
          yarn run build

      - name: Run Backend tests
        working-directory: backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: npm test

      # optional: ensure root deps resolved (matches ref step)
      - name: npm ci (root)
        run: npm ci || true

      # CD bits (write .env on server for backend)
      - name: Write backend .env from PROD secret
        run: |
          cd backend
          rm -f .env
          echo "${{ secrets.PROD }}" > .env

      - name: Start/Restart PM2 apps
        run: |
          pm2 start all || true
          pm2 restart all || true
